---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: hello
  namespace: demo
  labels:
    public-api: "false"    ## labels for matching only some Mappings
    documented: "false"    ## (note that "true" must be quoted)
spec:
  prefix: /hello/
  host: aes-demo.mturner.k736.net
  service: hello.demo:80
  docs:
    path: /.ambassador-internal/openapi-docs
---
