---
apiVersion: v1
kind: Service
metadata:
  name: quote-backend
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: https
    port: 443
    targetPort: 8000
  selector:
    app: quote
---